---
name: Test workflow scripts
permissions:
  contents: read

on:
  push:
    paths:
      - '.github/scripts/**'
      - '.github/workflows/scripts-tests.yml'
  pull_request:
    paths:
      - '.github/scripts/**'
      - '.github/workflows/scripts-tests.yml'
  workflow_dispatch:

jobs:
  unittest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        name: Install Python
        with:
          python-version: '3.12'
      - run: python3 -m unittest discover --start-directory .github/scripts --verbose
        name: Run script tests
